### ISSUE TITLE
Find the music sheet of the songs (Songsterr API)

### ISSUE THREAD

**Issue by annacosta99** [MattiaBrocco/Brain-Chain-LSPD-2020#3]
Developing the songsterr API for our scenario.
At the moment there are some problems with the json output. Maybe the problem is that the API doesn't allow the JSON format. Please help me to solve them. 
You will find it in the branch songsterr_Anna

**Comment by MattiaBrocco** [comment]
Fixed the issue by printing the link of the song inputted by the user
