### ISSUE TITLE
Csv file

### ISSUE THREAD

**Issue by alecancellari** [MattiaBrocco/Brain-Chain-LSPD-2020#5]
I tried to develop a function to create a .csv file. I stopped here because I don’t know how to go on. Please help me with the implementation

**Comment by MattiaBrocco** [comment]
### Progress
With the commit `bb16d9b` I added the if/else block to define whether to append to or write a new .csv from what you have done! The output is now a `pandas.DataFrame`. Added also a new option (-history) to allow users to check for the history of searches.
`main.py` now contains more exceptions!

**To Do**: decide whether to display the most recent queries or the most searched ones

**Comment by alecancellari** [comment]
Final decision most searched songs
